version: '3.9'

services:

  postgres:
    container_name: "postgres"
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=se_school
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    stop_grace_period: "3s"
    networks:
      - services-network

  api:
    container_name: "api"
    build: .
    ports:
      - '8080:8080'
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres:5432/se_school?sslmode=disable
      - API_TOKEN=d8352ceed37473851425d118
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
    depends_on:
      postgres:
        condition: service_healthy
    stop_grace_period: "5s"
    command: [ "/app/main" ]
    networks:
      - services-network

networks:
  services-network:
    driver: bridge
