// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateSubscription(ctx context.Context, email interface{}) (Subscription, error)
	GetSubscriptionByEmail(ctx context.Context, email interface{}) (Subscription, error)
	GetSubscriptions(ctx context.Context) ([]Subscription, error)
}

var _ Querier = (*Queries)(nil)
